# Generated by Django 5.0.4 on 2024-04-30 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cms", "0035_auto_20230822_2208"),
        ("mvs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MilitaryVehicleClassPluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "mv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mvs.militaryvehicleclass",
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
    ]
